# This is the grammar file for
# our simple calculator.

# Skipper's define the pattern
# that applies between lexical
# elements.
skipper = ([ \t\r\n]|\#.*)*

val = -?[0-9]+

# A c-language identifier
name = [a-zA-Z][a-zA-Z0-9_]*

# Parenthetical expression
paren = \( {add} \)

term = ({val}|{paren}|{name})

# patterns for the operators
mulop = [*/]
addop = [+-]

mul = {term}( {mulop} {term})*
add = {mul}( {addop} {mul})*
assign = {name} = {add}

expr = ^( {assign})* {add} $
